### ISSUE TITLE
[Bug] Error: ... node_sqlite3.node ... invalid ELF header

### ISSUE THREAD

**Issue by epicylon** [ekky-llc/spt-raid-review#17]
```
Realism: Questing Bots Detected, Making Adjustments

Realism: SWAG Detected, Making Adjustments

Realism: SAIN Detected, Making Adjustments

The application had a critical error and failed to run

Exception produced: Error

Stacktrace:

Error: /opt/server/user/mods/raid_review__0.0.3/node_modules/sqlite3/build/Release/node_sqlite3.node: invalid ELF header

    at process.dlopen (pkg/prelude/bootstrap.js:2255:28)

    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1473:18)

    at Module.load (node:internal/modules/cjs/loader:1207:32)

    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)

    at Module.require (node:internal/modules/cjs/loader:1235:19)

    at Module.require (pkg/prelude/bootstrap.js:1851:31)

    at require (node:internal/modules/helpers:176:18)

    at bindings (/opt/server/user/mods/raid_review__0.0.3/node_modules/bindings/bindings.js:112:48)

    at Object.<anonymous> (/opt/server/user/mods/raid_review__0.0.3/node_modules/sqlite3/lib/sqlite3-binding.js:1:37)

    at Module._compile (node:internal/modules/cjs/loader:1376:14)

```

**Comment by christopher-talke** [comment]
@epicylon thanks for the issue, interesting...

- What operating system are you running?
- What SPT version are you running?
- What Mod version are you running?

**Comment by RavenX8** [comment]
> @epicylon thanks for the issue, interesting...
> 
>     * What operating system are you running?
> 
>     * What SPT version are you running?
> 
>     * What Mod version are you running?

I am also getting this issue. I think it might be that sqlite3 might have different binary files based on what OS you are using, so you would need to manually run npm install on the target os  (which I'll attempt once I have the time).

I'm running Arch Linux
SPT 3.8.3
Mod version 0.0.3

**Comment by RavenX8** [comment]
So I was correct about the `node_modules` directory. To fix this issue, I deleted the `node_modules` directory then ran `npm install` to rebuild the directory. Started the SPT server and BAM! it no longer errors out.

**Comment by christopher-talke** [comment]
Thank you @RavenX8, I had a feeling that this would be an Operating System / Dependency conflict, I'll make sure to package a .gzip for linux users as well.

**Comment by christopher-talke** [comment]
New release includes linux download, hopefully that works out for those guys!
