### ISSUE TITLE
127.0.0.1 isn't my localhost

### ISSUE THREAD

**Issue by epicylon** [ekky-llc/spt-raid-review#58]
I can't figure out how I can change my localhost to `192.168.1.X`, because `127.0.0.1` isn't reachable for me.

I saw a reference to parts of the same issue in #19, but I can't find the reference folder structure (I'm on Linux).

**Comment by ekky1328** [comment]
Can you give me a rundown on your setup/environment, and I'll figure out what you need.

**Comment by epicylon** [comment]
Yep! Nothing fancy over here.

- OpenMediaVault rack running Linux.
- FIKA dockerized with [https://github.com/OnniSaarni/SPT-Fika-Docker-Guide](https://github.com/OnniSaarni/SPT-Fika-Docker-Guide)
- I connect via SMB to user/mods folder on Linux server.

Let me know if I have to get more specific!

**Comment by epicylon** [comment]
Ping to avoid stale.

**Comment by phr0z** [comment]
I'm running the same setup as epicylon.

I can see this in my SPT Server console (after it downloaded the required dependencies)

```
Mod: raid_review__0.2.0 package.json requires name property
Mod: raid_review__0.2.0 package.json requires author property
Mod: raid_review__0.2.0 package.json requires version property
Mod: raid_review__0.2.0 package.json requires license property
Mod: raid_review__0.2.0 package.json contains an invalid version string
```
It doesn't seem to be running or it's not opening any ports
```

tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6971            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6970            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6969            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6972            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.54:53           0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::6971                 :::*                    LISTEN
tcp6       0      0 :::6970                 :::*                    LISTEN
tcp6       0      0 :::6969                 :::*                    LISTEN
tcp6       0      0 :::6972                 :::*                    LISTEN
tcp6       0    196 x.x.x.x:22       x.x.x.x:62919       ESTABLISHED
tcp6       0      0 x.x.x.x:22        x.x.x.x:54892       ESTABLISHED
tcp6       0      0 x.x.x.x:22        x.x.x.x:59333       ESTABLISHED
udp        0      0 127.0.0.54:53           0.0.0.0:*
udp        0      0 127.0.0.53:53           0.0.0.0:*
udp        0      0 x.x.x.x:68        0.0.0.0:*
raw6       0      0 :::58                   :::*                    7
```

**Comment by phr0z** [comment]
It crashes with error message.

```
The application had a critical error and failed to run
Exception produced: Error


Stacktrace:
Error: Command failed: "/opt/server/SPT_Data/Server/@pnpm/exe/pnpm" install adm-zip@^0.5.10 bezier-js@^6.1.4 compression@^1.7.4 cookie-parser@^1.4.6 cors@^2.8.5 express@^4.18.2 express-basic-auth@^1.2.1 lodash@^4.17.21 moment@^2.30.1 node-cron@^3.0.3 sqlite@^5.1.1 sqlite3@^5.1.7
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at PreSptModLoader.autoInstallDependencies (/snapshot/src/loaders/PreSptModLoader.ts:493:17)
    at PreSptModLoader.importModsAsync (/snapshot/src/loaders/PreSptModLoader.ts:158:22)
    at PreSptModLoader.load (/snapshot/src/loaders/PreSptModLoader.ts:54:24)
    at Program.start (/snapshot/src/Program.ts:25:35)
    at Object.<anonymous> (/snapshot/src/ide/ReleaseEntry.ts:19:9)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
```

**Comment by ekky1328** [comment]
Sorry @epicylon and @phr0z, is this still an issue for you guys?

I have been away on a trip since August and have just returned, still need help here?

**Comment by UnInfamous** [comment]
I'm getting the same experience as @phr0z. Used to work on 3.9. Now on 3.10, I've done a clean install of everything using https://github.com/zhliau/fika-spt-server-docker.

**Comment by robpneu** [comment]
@UnInfamous @phr0z are you running ‘npm install‘ manually or are you setting the spt download dependencies flag to true?

**Comment by UnInfamous** [comment]
> @UnInfamous @phr0z are you running ‘npm install‘ manually or are you setting the spt download dependencies flag to true?

I set the spt download dependencies to true.

**Comment by ekky1328** [comment]
@UnInfamous okay - try do an `npm install` instead.

I need to switch the project from `npm` to use `pnpm` which is what the SPT Server uses, I'm like 95% sure this the root cause of the issue behind the `dependencies flag` being set to `true`.

**Comment by robpneu** [comment]
Agreed. I’ve never gotten the auto install dependencies to work with raid review (though I’ve only ever tried it with raid review so 🤷‍♂️)

**Comment by ekky1328** [comment]
I'll see what I can do about migrating the project to PNPM soon enough, might not have a job in a few days, so might have some free time to throw at Raid Review improvements.
