### ISSUE TITLE
[Bug] Error after first installation

### ISSUE THREAD

**Issue by valentimarco** [ekky-llc/spt-raid-review#7]
After installing it, the server starts and crash with this stacktrace:
```powershell
┌─────────────────────────────────────────┐
│ SPT-AKI 3.8.3                           │
│ https://discord.sp-tarkov.com           │
│                                         │
│ This work is free of charge             │
│ If you paid money, you were scammed     │
│ Commercial use is prohibited            │
└─────────────────────────────────────────┘
ModLoader: loading 21 server mods...
Installing dependencies for Mod: raid-review by: ekky
The application had a critical error and failed to run
Exception produced: Error

Stacktrace:
Error: Command failed: E:\SPT\Aki_Data\Server\@pnpm\exe\pnpm.exe install adm-zip@^0.5.10 bezier-js@^6.1.4 cors@^2.8.5 express@^4.18.2 lodash@^4.17.21 moment@^2.30.1 sqlite@^5.1.1 sqlite3@^5.1.7
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at PreAkiModLoader.autoInstallDependencies (C:\snapshot\src\loaders\PreAkiModLoader.ts:556:17)
    at PreAkiModLoader.importModsAsync (C:\snapshot\src\loaders\PreAkiModLoader.ts:181:22)
    at PreAkiModLoader.load (C:\snapshot\src\loaders\PreAkiModLoader.ts:58:24)
    at Program.start (C:\snapshot\src\Program.ts:30:35)
    at Object.<anonymous> (C:\snapshot\src\ide\ReleaseEntry.ts:19:9)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
```
Ones i reopen the server, i get this log:
```powershell
Commit hash: 01783e295be916352ccb1078cf8351b273610c8e
Build date: 1715594841109
┌─────────────────────────────────────────┐
│ SPT-AKI 3.8.3                           │
│ https://discord.sp-tarkov.com           │
│                                         │
│ This work is free of charge             │
│ If you paid money, you were scammed     │
│ Commercial use is prohibited            │
└─────────────────────────────────────────┘
ModLoader: loading 21 server mods...
Mod raid_review__0.0.1 package.json requires name property
Mod raid_review__0.0.1 package.json requires author property
Mod raid_review__0.0.1 package.json requires version property
Mod raid_review__0.0.1 package.json requires license property
Mod raid_review__0.0.1 package.json contains an invalid version string
```
And the package.json is an empty object...

P.S first time with spt mods and idk where are the log files...

**Comment by christopher-talke** [comment]
@valentimarco  This is a fix another user tested, and worked for them:

> Delete the mod in the mods folder and the bepinex plugin, download [Node.js](https://nodejs.org/en) and [Pnpm](https://pnpm.io/installation) and make sure `autoInstallModDependencies` is `true` in `<SPT-Install>/Aki_Data/Server/configs/core.json`, 
then copy and paste the mod files back in.

I don't see why that would cause fix it, but I'm going to do some testing to try and recreate the bug.

**Comment by christopher-talke** [comment]
v0.0.2 ships with `node_modules` and all required dependencies, negates the need to do any funky stuff with installation steps (for now).
